name: Release on GitHub & PyPI

on:
  push:

env:
  CMEEL_JOBS: 2
  CMEEL_LOG_LEVEL: DEBUG

jobs:
  macos:
    name: "macos"
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: python -m pip wheel -vw wh .
        env:
          CMEEL_JOBS: 2
          CMEEL_CMAKE_ARGS: "-DSYSTEM_INCLUDEDIR=/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
      - uses: actions/upload-artifact@v3
        with:
          path: wh
