name: Release on GitHub & PyPI

on:
  push:

env:
  CMEEL_JOBS: 2
  CMEEL_LOG_LEVEL: DEBUG

jobs:
  macos:
    name: "macos"
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: ls /
      - run: ls /Users
      - run: ls /Users/*
      - run: find /Applications -name MacOSX.platform
      - run: find /Applications -name MacOSX.sdk
      #- run: python -m pip wheel -vw wh .
        #env:
          #CMEEL_JOBS: 1
      - uses: actions/upload-artifact@v3
        with:
          path: wh
